# Generated by Django 3.0.8 on 2020-07-28 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import froala_editor.fields
import leads.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('content', froala_editor.fields.FroalaField(verbose_name='Содержание')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=leads.utils.avatar_upload)),
            ],
            options={
                'verbose_name': 'Аватар',
                'verbose_name_plural': 'Аватар',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=leads.utils.certificate_upload, verbose_name='Сертификат')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('token', models.CharField(blank=True, max_length=40, null=True, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', froala_editor.fields.FroalaField(verbose_name='Содержание')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MassageSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало')),
                ('end_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Конец')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('active', models.BooleanField(default=True, verbose_name='Действительна')),
                ('constant', models.BooleanField(default=False, verbose_name='Постоянна')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.Client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Cеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ['-start_time'],
            },
        ),
    ]
