# Generated by Django 3.0.8 on 2020-08-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='client',
            name='notify',
            field=models.BooleanField(default=False, verbose_name='Оповещать'),
        ),
    ]
